#!/usr/bin/env python3
"""Validate an HTML FTO report-quality assessment and produce a QA harness.

This is the localized counterpart of the source validator. It preserves the
source package's structural, visual, content, scoring, and cross-field checks,
while applying evidence-safe terminology for international FTO practice.

The validator does not decide freedom to operate. It checks whether a report
generated by this package is structurally complete, internally consistent,
transparent about its evidence, and appropriately qualified.

Usage:
    python validate_report.py report.html [--out-dir qa-output]
    python validate_report.py report.html --expected-css-sha256 HASH

Outputs:
    validation.json
    validation.html

Exit codes:
    0  no failed fatal or error checks
    1  at least one failed fatal or error check
    2  input or command-line error
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path


EXPECTED_SECTIONS = [
    "Report identity and scope",
    "Executive summary",
    "Three-layer review overview",
    "Four-dimension scorecard",
    "Independent-search comparison and omissions",
    "Search-topic fit",
    "Search-scope coverage",
    "Claim-comparison rigor",
    "Higher-risk patent list",
    "Moderate-risk patent list",
    "Lower-risk patent list",
    "Response-measure quality",
    "Risk-mitigation recommendations",
    "Consolidated issue register",
    "Conclusion and remediation plan",
    "Review boundary and disclaimer",
]

REQUIRED_CLASSES = {
    "card",
    "verify",
    "mitigation",
    "chapter-no",
    "dim",
    "bar",
    "bar-fill",
    "fatal-banner",
    "scene-badge",
}

REQUIRED_CONCEPTS = {
    "target market": ("target market", "jurisdiction"),
    "product or process version": ("product version", "process version", "technical version", "product or technology"),
    "search cutoff": ("search cutoff", "cutoff date"),
    "status date": ("legal-status date", "status date"),
    "family counting rule": ("family counting", "family rule"),
    "claim version": ("claim version", "claim text version", "claims reviewed"),
    "independent routes": ("semantic", "keyword", "classification", "assignee"),
    "pending watchlist": ("pending application", "watchlist"),
}

ABSOLUTE_LEGAL_LANGUAGE = (
    "guaranteed freedom to operate",
    "zero infringement risk",
    "cannot infringe",
    "will not infringe",
    "no patent risk exists",
    "legally safe in all jurisdictions",
)

FALSE_VERIFICATION_LANGUAGE = (
    "verified in real time" ,
    "live status confirmed",
    "complete recall established",
    "all relevant patents found",
    "recall is 100%",
)

INLINE_STYLE_RE = re.compile(r"\sstyle\s*=", re.I)
SCRIPT_RE = re.compile(r"<script\b", re.I)
STYLE_RE = re.compile(r"<style(?:\s[^>]*)?>(.*?)</style>", re.I | re.S)
H2_RE = re.compile(r"<h2(?:\s[^>]*)?>(.*?)</h2>", re.I | re.S)
TAG_RE = re.compile(r"<[^>]+>")
LINK_RE = re.compile(r"<a\b[^>]*\bhref\s*=\s*([\"'])(.*?)\1", re.I | re.S)
CLASS_RE = re.compile(r"\bclass\s*=\s*([\"'])(.*?)\1", re.I | re.S)


@dataclass
class Check:
    """One machine-readable harness result."""

    id: str
    group: str
    name: str
    passed: bool
    fail_severity: str
    observed: str
    expected: str
    remediation: str


def strip_tags(fragment: str) -> str:
    """Return normalized human-readable text from a small HTML fragment."""

    without_tags = TAG_RE.sub(" ", fragment)
    return re.sub(r"\s+", " ", html.unescape(without_tags)).strip()


def extract_style(html_text: str) -> tuple[str, str]:
    """Return the single embedded stylesheet and a diagnostic message."""

    matches = STYLE_RE.findall(html_text)
    if len(matches) != 1:
        return "", f"found {len(matches)} embedded style blocks"
    return matches[0], "found exactly one embedded style block"


def extract_h2_titles(html_text: str) -> list[str]:
    """Extract normalized H2 labels in document order."""

    return [
        re.sub(r"^\s*\d+\.\s*", "", strip_tags(value))
        for value in H2_RE.findall(html_text)
    ]


def find_section_body(html_text: str, title: str) -> str:
    """Return the HTML between a named H2 and the next H2."""

    headings = list(re.finditer(r"<h2(?:\s[^>]*)?>(.*?)</h2>", html_text, re.I | re.S))
    for index, heading in enumerate(headings):
        normalized = re.sub(r"^\s*\d+\.\s*", "", strip_tags(heading.group(1)))
        if normalized.lower() == title.lower():
            start = heading.end()
            end = headings[index + 1].start() if index + 1 < len(headings) else len(html_text)
            return html_text[start:end]
    return ""


def add(
    checks: list[Check],
    id_: str,
    group: str,
    name: str,
    ok: bool,
    fail_severity: str,
    observed: str,
    expected: str,
    remediation: str,
) -> None:
    """Append a check without silently altering its severity."""

    checks.append(
        Check(
            id=id_,
            group=group,
            name=name,
            passed=bool(ok),
            fail_severity=fail_severity,
            observed=observed,
            expected=expected,
            remediation=remediation,
        )
    )


def extract_score(text: str) -> float | None:
    """Read a score expressed as `overall score: N` or `N/100`."""

    patterns = (
        r"overall\s+(?:quality\s+)?score\s*[:=]\s*(\d+(?:\.\d+)?)",
        r"\b(\d+(?:\.\d+)?)\s*/\s*100\b",
    )
    for pattern in patterns:
        match = re.search(pattern, text, re.I)
        if match:
            return float(match.group(1))
    return None


def extract_grade(text: str) -> str | None:
    """Read the localized quality grade, including the fatal override."""

    match = re.search(
        r"quality\s+grade\s*[:=]\s*"
        r"(excellent|good|adequate|needs improvement|unsatisfactory|not scored|fatal)",
        text,
        re.I,
    )
    return match.group(1).lower() if match else None


def grade_matches(score: float | None, grade: str | None, fatal: bool) -> bool:
    """Apply the source grade bands, with fatal defects as an override."""

    if fatal:
        return grade == "fatal"
    if score is None or grade is None or grade == "not scored":
        return True
    expected = (
        "excellent" if score >= 90 else
        "good" if score >= 80 else
        "adequate" if score >= 70 else
        "needs improvement" if score >= 60 else
        "unsatisfactory"
    )
    return grade == expected


def parse_count_near(text: str, labels: tuple[str, ...]) -> int | None:
    """Read an integer next to any accepted label."""

    for label in labels:
        match = re.search(re.escape(label) + r"\s*[:=]\s*(\d+)", text, re.I)
        if match:
            return int(match.group(1))
    return None


def classes_in(html_text: str) -> set[str]:
    """Collect every class token used by the document."""

    values: set[str] = set()
    for _, raw in CLASS_RE.findall(html_text):
        values.update(raw.split())
    return values


def validate(html_path: Path, expected_css_sha256: str | None = None) -> dict:
    """Run the localized structural and evidence-safety harness."""

    html_text = html_path.read_text(encoding="utf-8")
    plain = strip_tags(html_text)
    lower = plain.lower()
    checks: list[Check] = []

    add(checks, "S-01", "Structure", "HTML language", bool(re.search(r"<html\b[^>]*\blang=[\"']en[\"']", html_text, re.I)), "error", "lang=en" if "lang=\"en\"" in html_text or "lang='en'" in html_text else "missing", "The root element declares English.", "Set <html lang=\"en\">.")
    add(checks, "S-02", "Structure", "Document title", bool(re.search(r"<title>\s*[^<]+\s*</title>", html_text, re.I)), "error", "present" if "<title" in html_text.lower() else "missing", "A non-empty HTML title is present.", "Add a descriptive report title.")

    titles = extract_h2_titles(html_text)
    exact_sections = titles == EXPECTED_SECTIONS
    add(checks, "S-03", "Structure", "Sixteen-section contract", exact_sections, "fatal", f"observed {len(titles)} sections: {titles}", f"exactly {len(EXPECTED_SECTIONS)} sections in the documented order", "Regenerate the report with generate_report.py and do not rename or reorder required sections.")

    for index, title in enumerate(EXPECTED_SECTIONS, 1):
        body = find_section_body(html_text, title)
        meaningful = len(strip_tags(body)) >= 20
        add(checks, f"S-{index + 3:02d}", "Structure", f"Section {index}: {title}", meaningful, "error", f"{len(strip_tags(body))} visible characters", "The section exists and contains meaningful evidence or an explicit missing-evidence statement.", "Populate the section or state what evidence is missing and how to obtain it.")

    style_text, style_observed = extract_style(html_text)
    add(checks, "V-01", "Visual", "Single fixed stylesheet", bool(style_text), "error", style_observed, "Exactly one non-empty embedded stylesheet.", "Embed the package stylesheet once through the generator.")

    css_hash = hashlib.sha256(style_text.encode("utf-8")).hexdigest() if style_text else ""
    if expected_css_sha256:
        add(checks, "V-02", "Visual", "Stylesheet integrity", css_hash == expected_css_sha256.lower(), "error", css_hash or "unavailable", expected_css_sha256.lower(), "Use the reviewed fto_report.css without ad hoc report-specific changes.")
    else:
        add(checks, "V-02", "Visual", "Stylesheet fingerprint recorded", bool(css_hash), "info", css_hash or "unavailable", "A SHA-256 fingerprint is recorded for review traceability.", "Regenerate with the fixed stylesheet.")

    inline_count = len(INLINE_STYLE_RE.findall(html_text))
    add(checks, "V-03", "Visual", "No inline style attributes", inline_count == 0, "error", str(inline_count), "0", "Move presentation rules into fto_report.css.")

    script_count = len(SCRIPT_RE.findall(html_text))
    add(checks, "V-04", "Visual", "No client-side scripts", script_count == 0, "warning", str(script_count), "0 for the stable HTML-only output", "Remove script elements and render evidence as static accessible HTML.")

    used_classes = classes_in(html_text)
    declared_classes = {
        match.group(1)
        for match in re.finditer(r"\.([A-Za-z_][A-Za-z0-9_-]*)", style_text)
    }
    missing_classes = sorted(REQUIRED_CLASSES - (used_classes | declared_classes))
    add(checks, "V-05", "Visual", "Required semantic classes", not missing_classes, "warning", f"missing: {missing_classes}" if missing_classes else "all required classes used", "The source package's report semantics remain represented.", "Use the generator's standard modules and class names.")

    unsafe_links: list[str] = []
    for _, url in LINK_RE.findall(html_text):
        normalized = html.unescape(url).strip()
        if not re.match(r"^https?://", normalized, re.I):
            unsafe_links.append(normalized)
    add(checks, "V-06", "Visual", "Safe external links", not unsafe_links, "error", f"unsafe: {unsafe_links}" if unsafe_links else "all links use HTTP(S)", "Only evidence links with an http or https scheme are emitted.", "Remove or normalize non-HTTP(S) links in the input data.")

    for offset, (concept, alternatives) in enumerate(REQUIRED_CONCEPTS.items(), 1):
        present = any(term in lower for term in alternatives)
        add(checks, f"E-{offset:02d}", "Evidence", concept.title(), present, "error", "present" if present else "missing", f"At least one of: {', '.join(alternatives)}", f"Add the report field and cite the supporting source or mark it unavailable.")

    prohibited_legal = [phrase for phrase in ABSOLUTE_LEGAL_LANGUAGE if phrase in lower]
    add(checks, "L-01", "Legal qualification", "No absolute non-infringement assurance", not prohibited_legal, "fatal", f"found: {prohibited_legal}" if prohibited_legal else "none found", "Conclusions are jurisdiction-, date-, product-, claim-, and evidence-specific.", "Replace absolute assurance with a qualified risk assessment and counsel-review boundary.")

    false_verification = [phrase for phrase in FALSE_VERIFICATION_LANGUAGE if phrase in lower]
    add(checks, "L-02", "Legal qualification", "No unsupported verification claim", not false_verification, "fatal", f"found: {false_verification}" if false_verification else "none found", "The report distinguishes observed evidence from live verification and unmeasured recall.", "Remove the claim or attach reproducible evidence supporting it.")

    score = extract_score(plain)
    grade = extract_grade(plain)
    fatal_banner = bool(re.search(r"class=[\"'][^\"']*fatal-banner[^\"']*[\"']", html_text, re.I))
    fatal = fatal_banner or grade == "fatal"
    add(checks, "C-01", "Consistency", "Score is within range", score is None or 0 <= score <= 100, "error", "not scored" if score is None else str(score), "No score, or a score from 0 through 100.", "Correct the numerical score and dimension arithmetic.")
    add(checks, "C-02", "Consistency", "Score, grade, and fatal override agree", grade_matches(score, grade, fatal), "fatal", f"score={score}, grade={grade}, fatal={fatal}", "The grade follows the documented bands; any fatal defect forces Fatal.", "Reconcile the scorecard, grade label, and fatal-defect state.")

    high_count = parse_count_near(plain, ("higher-risk patents", "high-risk patents"))
    action_count = parse_count_near(plain, ("mitigation actions", "recommended actions"))
    high_section = strip_tags(find_section_body(html_text, "Higher-risk patent list"))
    recommendation_section = strip_tags(find_section_body(html_text, "Risk-mitigation recommendations"))
    high_evidence = (high_count or 0) > 0 or bool(re.search(r"\bhigh(?:er)?[- ]risk\b", high_section, re.I) and "none identified" not in high_section.lower())
    recommendations_present = (action_count or 0) > 0 or len(recommendation_section) >= 40 and "none provided" not in recommendation_section.lower()
    add(checks, "C-03", "Consistency", "Higher-risk findings have response measures", not high_evidence or recommendations_present, "error", f"higher-risk evidence={high_evidence}, recommendations={recommendations_present}", "Every higher-risk finding is linked to a prioritized response, owner, and decision point.", "Add claim-specific mitigation, design-around, status review, licensing, opinion, or monitoring actions as appropriate.")

    estimate_present = bool(re.search(r"(?:recall|coverage)\s+estimate\s*[:=]\s*(?:\d|[<>])", plain, re.I))
    qualification_present = any(term in lower for term in ("qualified heuristic", "assumptions", "capture independence", "not estimated"))
    add(checks, "C-04", "Consistency", "Recall estimate is qualified", not estimate_present or qualification_present, "error", f"numeric estimate={estimate_present}, qualification={qualification_present}", "No numeric recall estimate without stated estimator, assumptions, route definitions, and limitations.", "Report empirical route overlap and observed union; label any estimator as heuristic only when assumptions are supported.")

    pending_section = strip_tags(find_section_body(html_text, "Independent-search comparison and omissions")).lower()
    pending_as_right = bool(re.search(r"pending application.{0,80}(?:enforceable|infringed|infringement)", pending_section, re.I | re.S))
    add(checks, "L-03", "Legal qualification", "Pending applications treated as a watchlist", not pending_as_right, "error", "improper enforceability language found" if pending_as_right else "no improper language found", "Pending claims are monitored separately from currently enforceable claims.", "Move pending applications to the temporal watchlist and qualify future-claim uncertainty.")

    severity_rank = {"fatal": 4, "error": 3, "warning": 2, "info": 1}
    failed = [item for item in checks if not item.passed]
    maximum = max((severity_rank[item.fail_severity] for item in failed), default=0)
    status = "FAIL" if maximum >= 3 else "REVIEW" if maximum == 2 else "PASS"

    counts = {
        "total": len(checks),
        "passed": sum(item.passed for item in checks),
        "failed": len(failed),
        "fatal_failed": sum(not item.passed and item.fail_severity == "fatal" for item in checks),
        "error_failed": sum(not item.passed and item.fail_severity == "error" for item in checks),
        "warning_failed": sum(not item.passed and item.fail_severity == "warning" for item in checks),
    }
    return {
        "schema_version": "1.0-en",
        "validator": "review-fto-report-quality-ip",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "input": str(html_path.resolve()),
        "input_sha256": hashlib.sha256(html_path.read_bytes()).hexdigest(),
        "embedded_css_sha256": css_hash,
        "status": status,
        "counts": counts,
        "checks": [asdict(item) for item in checks],
        "boundary": "This harness validates report construction and internal consistency; it does not provide an FTO opinion.",
    }


def render_html(result: dict) -> str:
    """Render an accessible static harness report with fixed local CSS."""

    css_path = Path(__file__).resolve().parent.parent / "assets" / "harness_report.css"
    css = css_path.read_text(encoding="utf-8")
    rows = []
    for item in result["checks"]:
        state = "PASS" if item["passed"] else "FAIL"
        row_class = "pass" if item["passed"] else f"fail {item['fail_severity']}"
        rows.append(
            "<tr class=\"" + html.escape(row_class, quote=True) + "\">"
            f"<td>{html.escape(item['id'])}</td>"
            f"<td>{html.escape(item['group'])}</td>"
            f"<td>{html.escape(item['name'])}</td>"
            f"<td><strong>{state}</strong></td>"
            f"<td>{html.escape(item['fail_severity'])}</td>"
            f"<td>{html.escape(item['observed'])}</td>"
            f"<td>{html.escape(item['expected'])}</td>"
            f"<td>{html.escape(item['remediation'])}</td>"
            "</tr>"
        )
    counts = result["counts"]
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>FTO assessment validation harness</title>
<style>
{css}
</style>
</head>
<body>
<main>
<header>
<p class="eyebrow">PatSnap · report quality control</p>
<h1>FTO assessment validation harness</h1>
<p class="lede">Static checks for structure, evidence transparency, legal qualification, visual integrity, and cross-field consistency.</p>
</header>
<section class="summary" aria-labelledby="summary-title">
<h2 id="summary-title">Validation summary</h2>
<dl>
<div><dt>Status</dt><dd>{html.escape(result['status'])}</dd></div>
<div><dt>Checks</dt><dd>{counts['total']}</dd></div>
<div><dt>Passed</dt><dd>{counts['passed']}</dd></div>
<div><dt>Failed</dt><dd>{counts['failed']}</dd></div>
<div><dt>Input SHA-256</dt><dd><code>{html.escape(result['input_sha256'])}</code></dd></div>
</dl>
</section>
<section aria-labelledby="checks-title">
<h2 id="checks-title">Check register</h2>
<div class="table-wrap">
<table>
<caption>Machine-executed checks and required remediation</caption>
<thead><tr><th>ID</th><th>Group</th><th>Check</th><th>Result</th><th>Severity</th><th>Observed</th><th>Expected</th><th>Remediation</th></tr></thead>
<tbody>{''.join(rows)}</tbody>
</table>
</div>
</section>
<footer><p>{html.escape(result['boundary'])}</p></footer>
</main>
</body>
</html>
"""


def write_outputs(result: dict, out_dir: Path) -> tuple[Path, Path]:
    """Write JSON and HTML results without altering the assessed report."""

    out_dir.mkdir(parents=True, exist_ok=True)
    json_path = out_dir / "validation.json"
    html_path = out_dir / "validation.html"
    json_path.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    html_path.write_text(render_html(result), encoding="utf-8")
    return json_path, html_path


def build_parser() -> argparse.ArgumentParser:
    """Build the stable command-line interface."""

    parser = argparse.ArgumentParser(description="Validate an English FTO report-quality assessment.")
    parser.add_argument("report", type=Path, help="HTML report generated by generate_report.py")
    parser.add_argument("--out-dir", type=Path, default=None, help="Output directory; defaults to <report-stem>-validation")
    parser.add_argument("--expected-css-sha256", default=None, help="Optional reviewed CSS fingerprint")
    return parser


def main() -> int:
    """Validate the input, write the harness, and return a CI-friendly code."""

    args = build_parser().parse_args()
    if not args.report.is_file():
        print(f"Input report not found: {args.report}", file=sys.stderr)
        return 2
    try:
        result = validate(args.report, args.expected_css_sha256)
        out_dir = args.out_dir or args.report.with_name(args.report.stem + "-validation")
        json_path, html_path = write_outputs(result, out_dir)
    except (OSError, UnicodeError, ValueError) as exc:
        print(f"Validation failed: {exc}", file=sys.stderr)
        return 2
    print(json.dumps({"status": result["status"], "json": str(json_path), "html": str(html_path), "counts": result["counts"]}, indent=2))
    return 1 if result["status"] == "FAIL" else 0


if __name__ == "__main__":
    raise SystemExit(main())
